### ISSUE TITLE
Can't Install Halyard inside Docker image

### ISSUE THREAD

**Issue by zivbaz** [spinnaker/halyard#595] opened 2017-07-09 09:02 UTC
Hey,
I'm trying to install Halyard inside a Docker image.
The image I'm using is [ubuntu:14:04](https://hub.docker.com/r/library/ubuntu/).
I'm using this command to install Halyard:
```sudo bash ./InstallHalyard.sh --user halyard```

After some time the script is running, I'm getting the following error:

```
Setting up spinnaker-halyard (0.29.0-10) ...
halyard: unrecognized service
dpkg: error processing package spinnaker-halyard (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 spinnaker-halyard
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Is anyone know why this error happens?

BTW, no issues run it inside AWS EC2 instance!

Thanks,
Ziv

**Comment by mdirkse** [comment] 2017-07-12 11:28
Same problem here. Dockerfile to reproduce:

```
FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -y curl apt-transport-https software-properties-common python-software-properties
RUN curl -O https://raw.githubusercontent.com/spinnaker/halyard/master/install/stable/InstallHalyard.sh
RUN useradd spin
RUN bash InstallHalyard.sh --user spin
```

**Comment by mdirkse** [comment] 2017-07-12 11:36
The last line of the `postinstall.sh` script tries to run `service halyard restart`.

This fails because, while the install script writes a systemd file to `/lib/systemd/system/halyard.service`, it's of no use because the docker image doesn't run systemd.

**Comment by lwander** [comment] 2017-07-13 15:17
Sorry for the lame answer, but typically you don't want to run services with upstart in docker containers. [This explains it better than I could](https://stackoverflow.com/questions/28055715/running-services-upstart-init-d-in-a-container). 

A better solution would be to build halyard within the docker container using `./gradlew installDist` and then run the script produced in `halyard-web/build/install/halyard/bin/halyard` as the daemon, and `halyard-web/build/install/halyard/hal` as the CLI. From there you need to do some magic to get any required files mounted within the container. I don't have an easy solution for that, but will if anyone has any suggestions they are welcome here.

**Comment by bacher09** [comment] 2017-07-20 10:05
It would be great, if there will be already provided docker images. Something that already done for spinnaker services. So those ones who want to install it into docker container can use already built image.

**Comment by lwander** [comment] 2017-07-21 15:25
Closed by https://github.com/spinnaker/halyard/pull/620 - I'll have some getting started docs soon

**Closed by lwander** 2017-07-21 15:25 UTC
Labels: help wanted, installation
