### ISSUE TITLE
Configure SSL settings using hal

### ISSUE THREAD

**Issue by idoshamun** [spinnaker/halyard#285] opened 2017-03-27 12:04 UTC
I would like to configure the SSL settings from `hal`, my current workaround is to edit directly the configuration

**Comment by lwander** [comment] 2017-03-27 13:05
Thanks, I'm marking this as a duplicate of https://github.com/spinnaker/halyard/issues/221 since that bug encompasses setting all necessary bits for SSL to work on any platform.

**Closed by lwander** 2017-03-27 13:05 UTC
